import Link from "next/link";
import { ActivityTimeline } from "@/components/crm-ui";
import { money, moment } from "@/lib/crm";
import { requireContext } from "@/lib/auth";

const stages=["new","qualified","discovery","proposal","negotiation","won","lost"];
export default async function CrmPage(){const {supabase,organizationId}=await requireContext();const now=new Date().toISOString();const [opportunities,leads,activities,threads]=await Promise.all([
  supabase.from("opportunities").select("id,name,stage,status,estimated_value,currency,next_action_at").eq("organization_id",organizationId).is("archived_at",null).order("created_at",{ascending:false}),
  supabase.from("leads").select("id,title,status,next_action_at").eq("organization_id",organizationId).is("archived_at",null).not("next_action_at","is",null).lte("next_action_at",now).order("next_action_at").limit(8),
  supabase.from("crm_activities").select("id,activity_type,subject,body,occurred_at").eq("organization_id",organizationId).order("occurred_at",{ascending:false}).limit(8),
  supabase.from("email_threads").select("id,subject,status,last_message_at,provider").eq("organization_id",organizationId).order("last_message_at",{ascending:false,nullsFirst:false}).limit(6)
]);const opps=opportunities.data??[];const open=opps.filter(x=>x.status==="open"),won=opps.filter(x=>x.status==="won"),lost=opps.filter(x=>x.status==="lost");const pipeline=open.reduce((sum,x)=>sum+Number(x.estimated_value??0),0);const followUps=[...(leads.data??[]).map(x=>({id:x.id,label:x.title,kind:"Lead",when:x.next_action_at,href:`/crm/leads/${x.id}`})),...open.filter(x=>x.next_action_at&&x.next_action_at<=now).map(x=>({id:x.id,label:x.name,kind:"Opportunity",when:x.next_action_at,href:`/crm/opportunities/${x.id}`}))].sort((a,b)=>String(a.when).localeCompare(String(b.when))).slice(0,10);
return <><header className="crm-command-header"><div><span className="eyebrow">Sales division / governed records</span><h1>CRM Command</h1><p className="lede">Commercial relationships, pipeline, follow-ups, and persisted communication history. No provider or autonomous execution is connected.</p></div><div className="crm-metrics"><div><strong>{open.length}</strong><span>Open opportunities</span></div><div><strong>{money(pipeline)}</strong><span>Open pipeline</span></div><div><strong>{won.length}</strong><span>Won</span></div><div><strong>{lost.length}</strong><span>Lost</span></div></div></header>
<section className="crm-priority-grid"><div className="crm-panel follow-up-panel"><div className="panel-heading"><div><span className="section-index">01</span><h2>Follow-up watch</h2></div><Link href="/crm/leads">Leads →</Link></div>{followUps.length?followUps.map(item=><Link className="follow-up-row" href={item.href} key={`${item.kind}-${item.id}`}><div><span>{item.kind}</span><strong>{item.label}</strong></div><time>{moment(item.when)}</time></Link>):<div className="empty">No overdue follow-up items.</div>}</div>
<div className="crm-panel"><div className="panel-heading"><div><span className="section-index">02</span><h2>Pipeline overview</h2></div><Link href="/crm/opportunities">Open pipeline →</Link></div><div className="crm-pipeline">{stages.map(stage=>{const rows=opps.filter(x=>x.stage===stage);return <div key={stage}><header><span>{stage}</span><strong>{rows.length}</strong></header>{rows.slice(0,3).map(row=><Link key={row.id} href={`/crm/opportunities/${row.id}`}><span>{row.name}</span><strong>{money(row.estimated_value,row.currency)}</strong></Link>)}{!rows.length&&<small>Clear</small>}</div>})}</div></div></section>
<section className="crm-lower-grid"><div className="crm-panel"><div className="panel-heading"><div><span className="section-index">03</span><h2>Recent CRM activity</h2></div></div><ActivityTimeline activities={activities.data??[]}/></div><div className="crm-panel"><div className="panel-heading"><div><span className="section-index">04</span><h2>Recent email records</h2></div><Link href="/crm/email">Email foundation →</Link></div>{threads.data?.length?threads.data.map(thread=><Link className="email-thread-row" href="/crm/email" key={thread.id}><div><strong>{thread.subject||"Untitled thread"}</strong><span>{thread.provider} · {thread.status}</span></div><time>{moment(thread.last_message_at)}</time></Link>):<div className="empty">No persisted email threads. Provider integration is not connected.</div>}</div></section></>}
