import { describe, expect, it } from "vitest";
import { governAgentProposal, type AgentIntelligenceContext, type AgentProposal } from "../lib/domain/agent-intelligence";
import { advanceWorkflow, resumeWorkflow, startWorkflow, workflowAuditEvent, type WorkflowState, type WorkflowStep } from "../lib/domain/controlled-workflow";

const step = (values: Partial<WorkflowStep> = {}): WorkflowStep => ({ agentId: "a", responseMode: "RECOMMEND", reviewer: false, blocker: null, clarification: null, approvalRequired: false, handoffAgentId: null, reviewerAgentId: null, ...values });
const proposal = (values: Partial<AgentProposal> = {}): AgentProposal => ({ interpretedIntent: "specialist_work", responseMode: "EXECUTE", proposedAction: "Run tool", actionKey: "forbidden", targetTask: "Task", targetAgent: null, result: "Done", confidence: "high", blocker: null, clarificationRequest: null, approvalRequired: false, explanation: "Execute.", ...values });
const policyContext: AgentIntelligenceContext = { agent: { id: "a", name: "A", department: null, role: "Specialist", purpose: "Work", skills: [], tools: [] }, currentTask: { id: "task", title: "Task", status: "running", safeInputSummary: "Task" }, organization: { agents: [], tasks: [], approvals: [], events: [] }, governance: { previewMode: false, directMutationAllowed: false, externalActionsRequireApproval: true } };

describe("controlled multi-agent workflow", () => {
  it("completes a successful three-agent specialist/reviewer route", () => { let state = startWorkflow("task", "a", true); let result = advanceWorkflow(state, step({ responseMode: "DELEGATE", handoffAgentId: "b" })); expect(result.decision).toBe("continue"); state = result.state; result = advanceWorkflow(state, step({ agentId: "b", reviewerAgentId: "c" })); expect(result.decision).toBe("route_reviewer"); state = result.state; result = advanceWorkflow(state, step({ agentId: "c", reviewer: true })); expect(result).toMatchObject({ decision: "complete", state: { status: "completed", reviewed: true } }); });
  it("stops when a reviewer challenges", () => { const state = { ...startWorkflow("task", "r"), currentAgentId: "r" }; expect(advanceWorkflow(state, step({ agentId: "r", reviewer: true, responseMode: "CHALLENGE" })).decision).toBe("stop"); });
  it("stops on clarification", () => expect(advanceWorkflow(startWorkflow("task", "a"), step({ responseMode: "CLARIFY", clarification: "Which market?" })).decision).toBe("stop"));
  it("pauses for approval", () => expect(advanceWorkflow(startWorkflow("task", "a"), step({ responseMode: "REQUIRE_APPROVAL", approvalRequired: true })).decision).toBe("pause"));
  it("resumes only after approval", () => { const paused = advanceWorkflow(startWorkflow("task", "a"), step({ responseMode: "REQUIRE_APPROVAL", approvalRequired: true })).state; expect(resumeWorkflow(paused, "approved")).toMatchObject({ decision: "continue", state: { status: "active" } }); });
  it("stops after rejected approval", () => { const paused = advanceWorkflow(startWorkflow("task", "a"), step({ responseMode: "REQUIRE_APPROVAL", approvalRequired: true })).state; expect(resumeWorkflow(paused, "rejected")).toMatchObject({ decision: "stop", state: { status: "stopped" } }); });
  it("enforces the four-step maximum", () => { const state: WorkflowState = { ...startWorkflow("task", "e"), steps: ["a", "b", "c", "d"].map((agentId) => ({ agentId, responseMode: "DELEGATE", reviewer: false })), visitedAgentIds: ["a", "b", "c", "d"] }; expect(advanceWorkflow(state, step({ agentId: "e" }))).toMatchObject({ decision: "stop", reason: "Maximum workflow step limit reached." }); });
  it("blocks repeated A-B-A routing", () => { let state = advanceWorkflow(startWorkflow("task", "a"), step({ responseMode: "DELEGATE", handoffAgentId: "b" })).state; const result = advanceWorkflow(state, step({ agentId: "b", responseMode: "DELEGATE", handoffAgentId: "a" })); expect(result).toMatchObject({ decision: "stop", reason: "Repeated or self-directed handoff blocked." }); });
  it("blocks unauthorized specialist proposals", () => expect(governAgentProposal(proposal(), policyContext)).toMatchObject({ responseMode: "REFUSE", accepted: false }));
  it("creates safe workflow audit metadata", () => { const event = workflowAuditEvent("workflow.started", startWorkflow("task", "a")); expect(event).toMatchObject({ eventType: "workflow.started", metadata: { stepCount: 0, currentAgentId: "a" } }); expect(event.metadata).not.toHaveProperty("prompt"); });
});
